version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - iudigital-network

  main-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - iudigital-network

  project-service:
    build: ./iudigital-project-service
    ports:
      - "3001:3001"
    networks:
      - iudigital-network

  project-service-replica:
    build: ./iudigital-project-service
    networks:
      - iudigital-network

  load-balancer:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - project-service
      - project-service-replica
    networks:
      - iudigital-network

volumes:
  mongo-data:

networks:
  iudigital-network:
